# Permalinks
permalink:           pretty

# Setup
title:               WuKongDiary
tagline:             Wukong
url:                 https://github.com/legend91325
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              WuKong
  url:               https://github.com/legend91325
  email:             213dormitory@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/legend91325

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
